//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whats_Up.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [RegularExpression(@"([A-Za-z0-9]{3,})@([A-Za-z0-9]{3,})\.([A-Za-z0-9]{1,10})")]
        public string Email { get; set; }

        public string AddressLine { get; set; }
    }
}
