// <auto-generated />
namespace Whats_Up.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedfavoritemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedfavoritemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201812062356239_changedfavoritemodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
